export enum CommonResponseCodeEnum {
    SYSTEM_ERROR = 500,
    UNAUTHORIZED = 401,
    OTP_ERROR = 100,
    VERIFY_OTP_ERROR = 101,
    OTP_SUCCESS = 102,
    VERIFY_OTP_SUCCESS = 103,
    WRONG_OTP = 104,
    ONBOARDING_SUCCESS = 105,
    OTP_EXPIRED = 107,
    TOKENS_GENERATED = 108,
    USER_DO_NOT_EXIST = 109,
}